# Generated by Django 4.2.1 on 2023-05-11 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='comment',
            field=models.ManyToManyField(blank=True, to='flowers_store.comment', verbose_name='Отзывы на лот'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sales_role',
            field=models.BooleanField(default=False, verbose_name='Продавца'),
        ),
    ]
